apiVersion: v1
kind: Namespace
metadata:
  name: general
---
apiVersion: v1
kind: Service
metadata:
  name: admin-api
  namespace: general
spec:
  ports:
  - name: http
    port: 9086
    protocol: TCP
    targetPort: 9086
  selector:
    application: admin-api
